server:
  port: 9101
  address: 0.0.0.0

spring:
  config:
    additional-location: file:./.env.properties


  application:
    name: dding-user-profile-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 1001
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
