server:
  port: 9100
  address: 0.0.0.0
spring:
  config:
    additional-location: file:./.env.properties


  application:
      name: dding-user-auth-service
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/auth
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6379




  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_KEY}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_KEY}
            scope:
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
