server:
  port: ${SERVER_PORT:9100}
  address: 0.0.0.0
spring:
  config:
    import: optional:file:.env[.properties]


  application:
      name: dding-user-auth-service
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://host.docker.internal:3306/auth
      username: root
      password: 1001
  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: none

  data:
    redis:
      host: dding-board-redis
      port: 6379




kakao:
  client_id: 70ed7355473badad5a2e4bfac8e95bc6
  redirect_uri_mobile: http://10.0.2.2:9100/kakao/callback
  redirect_uri_pc: http://192.168.200.104:9100/kakao/callback
